spring:
  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp
  security:
    user:
      name: struts
      password: struts

  jpa:
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/struts
    username: root
    password: struts

management:
  endpoints:
    web:
      exposure:
        include: "*"
